easy_admin:
    entities:
        # List the entity class name you want to manage
        Category:
            class: App\Entity\Category

        Wallpaper:
            class: App\Entity\Wallpaper
            list:
                fields:
                    - "id"
                    - "filename"
                    - "slug"
                    - { property: "width", format: "%d" }
                    - { property: "height", format: "%d" }
                    - { property: "image", type: "image", base_path: "/img/" }
            form:
              fields:
                - "slug"
                - "width"
                - "height"




